name: Unit Tests

on:
  pull_request:
    branches:
      - main
      - release/*
  push:
    branches:
      - main
      - release/*
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Force Xcode 14.0
        run: sudo xcode-select -switch /Applications/Xcode_14.0.app
      - name: Build for iOS
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild build-for-testing -scheme ArcTests -destination "platform=iOS Simulator,OS=16.0,name=iPhone 14" | xcpretty
      - name: Run iOS tests
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild test-without-building -scheme ArcTests -destination "platform=iOS Simulator,OS=16.0,name=iPhone 14" | xcpretty

