name: Run tests

on:
  pull_request:
    branches:
      - master
      - Arc2.0_development
      - release/*
  push:
    branches:
      - master
      - Arc2.0_development
      - release/*

jobs:
  build:
    runs-on: macos-11
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
            submodules: recursive
      - name: Force Xcode 13.0
        run: sudo xcode-select -switch /Applications/Xcode_13.0.app
      - name: Build for iOS
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild build-for-testing -scheme ArcTests -destination "platform=iOS Simulator,OS=15.0,name=iPhone 13" | xcpretty
      - name: Run iOS tests
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild test-without-building -scheme ArcTests -destination "platform=iOS Simulator,OS=15.0,name=iPhone 13" | xcpretty
